import { API_KEY } from './constants.js'
export const STARS = []

export async function loadStars() {
	const data = [
		{ course: 'BOB', id: 1, name: 'Big Bob-omb on the Summit', difficulty: 2, time: 56660, active: true },
		{ course: 'BOB', id: 2, name: 'Footrace with Koopa the Quick', difficulty: 2, time: 82330, active: true },
		{ course: 'BOB', id: 3, name: 'Shoot to the Island in the Sky', difficulty: 2, time: 25160, active: true },
		{ course: 'BOB', id: 4, name: 'Find the 8 Red Coins', difficulty: 4, time: 80000, active: true },
		{ course: 'BOB', id: 5, name: 'Mario Wings to the Sky', difficulty: 3, time: 37100, active: true },
		{ course: 'BOB', id: 6, name: "Behind Chain Chomp's Gate", difficulty: 1, time: 12300, active: true },
		{ course: 'BOB', id: 7, name: 'BoB 100 Coins', difficulty: 5, time: 740940, active: true },
		{ course: 'WHOMPS', id: 8, name: "Chip off Whomp's Block", difficulty: 2, time: 31430, active: true },
		{ course: 'WHOMPS', id: 9, name: 'To the Top of the Fortress', difficulty: 2, time: 14960, active: true },
		{ course: 'WHOMPS', id: 10, name: 'Shoot into the Wild Blue', difficulty: 1, time: 11130, active: true },
		{ course: 'WHOMPS', id: 11, name: 'Red Coins on the Floating Isle', difficulty: 4, time: 43200, active: true },
		{ course: 'WHOMPS', id: 12, name: 'Fall onto the Caged Island', difficulty: 2, time: 14060, active: true },
		{ course: 'WHOMPS', id: 13, name: 'Blast Away the Wall', difficulty: 1, time: 8860, active: true },
		{ course: 'WHOMPS', id: 14, name: 'WF 100 Coins', difficulty: 4, time: 171870, active: true },
		{ course: 'JRB', id: 15, name: 'Plunder in the Sunken Ship', difficulty: 4, time: 129830, active: true },
		{ course: 'JRB', id: 16, name: 'Can the Eel Come out to Play?', difficulty: 3, time: 48400, active: true },
		{ course: 'JRB', id: 17, name: 'Treasure of the Ocean Cave', difficulty: 2, time: 69100, active: true },
		{ course: 'JRB', id: 18, name: 'Red Coins on the Ship Afloat', difficulty: 5, time: 144480, active: true },
		{ course: 'JRB', id: 19, name: 'Blast to the Stone Pillar', difficulty: 3, time: 13200, active: true },
		{ course: 'JRB', id: 20, name: 'Through the Jet Stream', difficulty: 4, time: 24860, active: true },
		{ course: 'JRB', id: 21, name: 'JRB 100 Coins', difficulty: 5, time: 562420, active: true },
		{ course: 'CCM', id: 22, name: "Slip Slidin' Away", difficulty: 1, time: 26630, active: true },
		{ course: 'CCM', id: 23, name: "Li'l Penguin Lost", difficulty: 2, time: 19700, active: true },
		{ course: 'CCM', id: 24, name: 'Big Penguin Race', difficulty: 4, time: 62730, active: true },
		{ course: 'CCM', id: 25, name: 'Frosty Slide for 8 Red Coins', difficulty: 3, time: 69200, active: true },
		{ course: 'CCM', id: 26, name: "Snowman's Lost His Head", difficulty: 2, time: 37430, active: true },
		{ course: 'CCM', id: 27, name: 'Wall Kicks Will Work', difficulty: 2, time: 10300, active: true },
		{ course: 'CCM', id: 28, name: 'CCM 100 Coins', difficulty: 5, time: 228620, active: true },
		{ course: 'BBH', id: 29, name: 'Go on a Ghost Hunt', difficulty: 2, time: 68760, active: true },
		{ course: 'BBH', id: 30, name: "Ride Big Boo's Merry-Go-Round", difficulty: 2, time: 40600, active: true },
		{ course: 'BBH', id: 31, name: 'Secret of the Haunted Books', difficulty: 2, time: 11600, active: true },
		{ course: 'BBH', id: 32, name: 'Seek the 8 Red Coins', difficulty: 3, time: 67100, active: true },
		{ course: 'BBH', id: 33, name: "Big Boo's Balcony", difficulty: 2, time: 32300, active: true },
		{ course: 'BBH', id: 34, name: 'Eye to Eye in the Secret Room', difficulty: 3, time: 31400, active: true },
		{ course: 'BBH', id: 35, name: 'BBH 100 Coins', difficulty: 3, time: 145240, active: true },
		{ course: 'HMC', id: 36, name: 'Swimming Beast in the Cavern', difficulty: 2, time: 17700, active: true },
		{ course: 'HMC', id: 37, name: 'Elevate for 8 Red Coins', difficulty: 4, time: 166460, active: true },
		{ course: 'HMC', id: 38, name: 'Metal-Head Mario Can Move!', difficulty: 3, time: 27600, active: true },
		{ course: 'HMC', id: 39, name: 'Navigating the Toxic Maze', difficulty: 3, time: 31200, active: true },
		{ course: 'HMC', id: 40, name: 'A-Maze-ing Emergency Exit', difficulty: 2, time: 11760, active: true },
		{ course: 'HMC', id: 41, name: 'Watch for Rolling Rocks', difficulty: 2, time: 16130, active: true },
		{ course: 'HMC', id: 42, name: 'HMC 100 Coins', difficulty: 5, time: 414410, active: true },
		{ course: 'LLL', id: 43, name: 'Boil the Big Bully', difficulty: 2, time: 20830, active: true },
		{ course: 'LLL', id: 44, name: 'Bully the Bullies', difficulty: 3, time: 25600, active: true },
		{ course: 'LLL', id: 45, name: '8-Coin Puzzle with 15 Pieces', difficulty: 2, time: 15130, active: true },
		{ course: 'LLL', id: 46, name: 'Red-Hot Log Rolling', difficulty: 3, time: 15760, active: true },
		{ course: 'LLL', id: 47, name: 'Hot-Foot-It into the Volcano', difficulty: 3, time: 24660, active: true },
		{ course: 'LLL', id: 48, name: 'Elevator Tour in the Volcano', difficulty: 2, time: 22660, active: true },
		{ course: 'LLL', id: 49, name: 'LLL 100 Coins', difficulty: 5, time: 352800, active: true },
		{ course: 'SSL', id: 50, name: 'In the Talons of the Big Bird', difficulty: 2, time: 17160, active: true },
		{ course: 'SSL', id: 51, name: 'Shining Atop the Pyramid', difficulty: 1, time: 7060, active: true },
		{ course: 'SSL', id: 52, name: 'Inside the Ancient Pyramid', difficulty: 4, time: 13530, active: true },
		{ course: 'SSL', id: 53, name: 'Stand Tall on the Four Pillars', difficulty: 3, time: 75060, active: true },
		{ course: 'SSL', id: 54, name: 'Free Flying for 8 Red Coins', difficulty: 5, time: 357650, active: true },
		{ course: 'SSL', id: 55, name: 'Pyramid Puzzle', difficulty: 5, time: 79930, active: true },
		{ course: 'SSL', id: 56, name: 'SSL 100 Coins', difficulty: 5, time: 710020, active: true },
		{ course: 'DDD', id: 57, name: "Board Bowser's Sub", difficulty: 2, time: 43930, active: true },
		{ course: 'DDD', id: 58, name: 'Chests in the Current', difficulty: 5, time: 125150, active: true },
		{ course: 'DDD', id: 59, name: 'Pole-Jumping for Red Coins', difficulty: 4, time: 188680, active: true },
		{ course: 'DDD', id: 60, name: 'Through the Jet Stream', difficulty: 4, time: 68960, active: true },
		{ course: 'DDD', id: 61, name: "The Manta Ray's Reward", difficulty: 4, time: 27200, active: true },
		{ course: 'DDD', id: 62, name: 'Collect the Caps...', difficulty: 3, time: 56550, active: true },
		{ course: 'DDD', id: 63, name: 'DDD 100 Coins', difficulty: 5, time: 540370, active: true },
		{ course: 'SL', id: 64, name: "Snowman's Big Head", difficulty: 3, time: 13800, active: true },
		{ course: 'SL', id: 65, name: 'Chill with the Bully', difficulty: 2, time: 12660, active: true },
		{ course: 'SL', id: 66, name: 'In the Deep Freeze', difficulty: 1, time: 5530, active: true },
		{ course: 'SL', id: 67, name: 'Whirl from the Freezing Pond', difficulty: 3, time: 14630, active: true },
		{ course: 'SL', id: 68, name: "Shell Shreddin' for Red Coins", difficulty: 4, time: 209640, active: true },
		{ course: 'SL', id: 69, name: 'Into the Igloo', difficulty: 3, time: 34800, active: true },
		{ course: 'SL', id: 70, name: 'SL 100 Coins', difficulty: 5, time: 175540, active: true },
		{ course: 'WDW', id: 71, name: 'Shocking Arrow Lifts!', difficulty: 1, time: 13860, active: true },
		{ course: 'WDW', id: 72, name: "Top o' the Town", difficulty: 3, time: 20130, active: true },
		{ course: 'WDW', id: 73, name: 'Secrets in the Shallows & Sky', difficulty: 4, time: 47000, active: true },
		{ course: 'WDW', id: 74, name: 'Express Elevator--Hurry Up!', difficulty: 3, time: 38430, active: true },
		{ course: 'WDW', id: 75, name: 'Go to Town for Red Coins', difficulty: 5, time: 136760, active: true },
		{ course: 'WDW', id: 76, name: 'Quick Race Through Downtown!', difficulty: 3, time: 61130, active: true },
		{ course: 'WDW', id: 77, name: 'WDW 100 Coins', difficulty: 5, time: 244540, active: true },
		{ course: 'TTM', id: 78, name: 'Scale the Mountain', difficulty: 3, time: 33030, active: true },
		{ course: 'TTM', id: 79, name: 'Mystery of the Monkey Cage', difficulty: 4, time: 57700, active: true },
		{ course: 'TTM', id: 80, name: "Scary 'Shrooms, Red Coins", difficulty: 4, time: 34400, active: true },
		{ course: 'TTM', id: 81, name: 'Mysterious Mountainside', difficulty: 1, time: 14730, active: true },
		{ course: 'TTM', id: 82, name: 'Breathtaking View from Bridge', difficulty: 3, time: 27460, active: true },
		{ course: 'TTM', id: 83, name: 'Blast to the Lonely Mushroom', difficulty: 2, time: 11830, active: true },
		{ course: 'TTM', id: 84, name: 'TTM 100 Coins', difficulty: 5, time: 559130, active: true },
		{ course: 'THI', id: 85, name: 'Pluck the Piranha Flower', difficulty: 3, time: 25730, active: true },
		{ course: 'THI', id: 86, name: 'The Tip Top of the Huge Island', difficulty: 2, time: 25560, active: true },
		{ course: 'THI', id: 87, name: 'Rematch with Koopa the Quick', difficulty: 3, time: 52400, active: true },
		{ course: 'THI', id: 88, name: 'Five Itty Bitty Secrets', difficulty: 4, time: 36700, active: true },
		{ course: 'THI', id: 89, name: "Wiggler's Red Coins", difficulty: 5, time: 59550, active: true },
		{ course: 'THI', id: 90, name: 'Make Wiggler Squirm', difficulty: 4, time: 55830, active: true },
		{ course: 'THI', id: 91, name: 'THI 100 Coins', difficulty: 5, time: 498430, active: true },
		{ course: 'TTC', id: 92, name: 'Roll into the Cage', difficulty: 3, time: 12560, active: true },
		{ course: 'TTC', id: 93, name: 'The Pit and the Pendulums', difficulty: 3, time: 16630, active: true },
		{ course: 'TTC', id: 94, name: 'Get a Hand', difficulty: 3, time: 9430, active: true },
		{ course: 'TTC', id: 95, name: 'Stomp on the Thwomp', difficulty: 3, time: 50150, active: true },
		{ course: 'TTC', id: 96, name: 'Timed Jumps on Moving Bars', difficulty: 3, time: 28030, active: true },
		{ course: 'TTC', id: 97, name: 'Stop Time for Red Coins', difficulty: 3, time: 20660, active: true },
		{ course: 'TTC', id: 98, name: 'TTC 100 Coins', difficulty: 4, time: 161720, active: true },
		{ course: 'RR', id: 99, name: 'Cruiser Crossing the Rainbow', difficulty: 3, time: 49900, active: true },
		{ course: 'RR', id: 100, name: 'The Big House in the Sky', difficulty: 4, time: 160290, active: true },
		{ course: 'RR', id: 101, name: 'Coins Amassed in a Maze', difficulty: 3, time: 28960, active: true },
		{ course: 'RR', id: 102, name: "Swingin' in the Breeze", difficulty: 3, time: 15830, active: true },
		{ course: 'RR', id: 103, name: 'Tricky Triangles!', difficulty: 3, time: 17860, active: true },
		{ course: 'RR', id: 104, name: 'Somewhere Over the Rainbow', difficulty: 5, time: 73630, active: true },
		{ course: 'RR', id: 105, name: 'RR 100 Coins', difficulty: 5, time: 223850, active: true },
		{ course: 'CASTLE', id: 106, name: 'Dark World', difficulty: 4, time: 33260, active: true },
		{ course: 'CASTLE', id: 107, name: 'Fire Sea', difficulty: 5, time: 49260, active: true },
		{ course: 'CASTLE', id: 108, name: 'Bits', difficulty: 3, time: 55350, active: true },
		{ course: 'CASTLE', id: 109, name: 'Wing Cap', difficulty: 5, time: 48040, active: true },
		{ course: 'CASTLE', id: 110, name: 'Vanish Cap', difficulty: 3, time: 45910, active: true },
		{ course: 'CASTLE', id: 111, name: 'Metal Cap', difficulty: 3, time: 38100, active: true },
		{ course: 'CASTLE', id: 112, name: 'PSS Box', difficulty: 1, time: 25260, active: true },
		{ course: 'CASTLE', id: 113, name: 'PSS Fast', difficulty: 1, time: 21260, active: true },
		{ course: 'CASTLE', id: 114, name: 'Wing Mario Over the Rainbow', difficulty: 5, time: 187850, active: true },
		{ course: 'CASTLE', id: 115, name: 'HMC Toad', difficulty: 1, time: 0, active: true },
		{ course: 'CASTLE', id: 116, name: 'Upstairs Toad', difficulty: 1, time: 0, active: true },
		{ course: 'CASTLE', id: 117, name: 'Tippy Toad', difficulty: 1, time: 0, active: true },
		{ course: 'CASTLE', id: 118, name: 'MIPS1', difficulty: 1, time: 0, active: true },
		{ course: 'CASTLE', id: 119, name: 'MIPS2', difficulty: 1, time: 0, active: true },
		{ course: 'CASTLE', id: 120, name: 'Secret Aquarium', difficulty: 5, time: 83230, active: true },
	]
	STARS.push(...data)
}

export async function loadStarsFromSheet() {
	const starResponse = await fetch(
		`https://sheets.googleapis.com/v4/spreadsheets/1PA9nm1sqMAxBNcDFVwa3qER7M2HHigKeFvborR8Vz9U/values/Stars?key=${API_KEY}`,
	)
	const stars = await starResponse.json()
	const courseResponse = await fetch(
		`https://sheets.googleapis.com/v4/spreadsheets/1PA9nm1sqMAxBNcDFVwa3qER7M2HHigKeFvborR8Vz9U/values/Courses?key=${API_KEY}`,
	)
	const courses = await courseResponse.json()
	let courseMap = courses.values.reduce((map, row, index) => {
		if (index === 0) return map // skip header
		const [courseId, name, tts] = row
		map[courseId] = { name, tts }
		return map
	}, {})
	const rows = stars.values
	rows.slice(1).forEach((row, index) => {
		if (index === 0) return // skip header
		const [id, course, name, difficulty, time] = row
		STARS.push({
			course: courseMap[course] ? courseMap[course].name : course,
			courseTTS: courseMap[course] ? courseMap[course].tts : course,
			id: parseInt(id, 10),
			name,
			difficulty: parseInt(difficulty, 10),
			time: parseInt(time, 10),
			active: true,
		})
	})
}
